SET TIMING ON;
SELECT COUNT(*) FROM ECOMMERCE WHERE MON_FIELD =02 AND YEAR_FIELD =2019;
SELECT YEAR_FIELD,SUM(PRICE) FROM ECOMMERCE GROUP BY YEAR_FIELD;

SELECT MON_FIELD,SUM(PRICE) FROM ECOMMERCE  WHERE YEAR_FIELD=2019 GROUP BY MON_FIELD ORDER BY MON_FIELD;
SELECT COUNTRY,COUNT(*) FROM ECOMMERCE GROUP BY COUNTRY;

SELECT DISTINCT PRODUCTNAME,YEAR_FIELD AS YEAR FROM ECOMMERCE 
GROUP BY PRODUCTNAME,YEAR_FIELD ORDER BY YEAR_FIELD;