SET TIMING ON;
/*
SELECT COUNT(*) FROM ECOMMERCE WHERE MON_FIELD =02 AND YEAR_FIELD =2019;
SELECT YEAR_FIELD,SUM(PRICE) FROM ECOMMERCE GROUP BY YEAR_FIELD;

SELECT MON_FIELD,SUM(PRICE) FROM ECOMMERCE  WHERE YEAR_FIELD=2019 GROUP BY MON_FIELD ORDER BY MON_FIELD;
SELECT COUNTRY,COUNT(*) FROM ECOMMERCE GROUP BY COUNTRY;

SELECT DISTINCT PRODUCTNAME,YEAR_FIELD AS YEAR FROM ECOMMERCE 
GROUP BY PRODUCTNAME,YEAR_FIELD ORDER BY YEAR_FIELD;
select * from SALES;
select * from ECOMMERCE;
DESC ECOMMERCE;
SELECT * FROM ECOMMERCE;

*/


SELECT COUNT(*) FROM ECOMMERCE WHERE substr(purchase_date,6,2) =02 AND substr(purchase_date,1,4) =2019;

EXPLAIN PLAN FOR SELECT COUNT(*) FROM ECOMMERCE WHERE substr(purchase_date,6,2) =02 AND substr(purchase_date,1,4) =2019;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());

SELECT substr(purchase_date,1,4),SUM(PRICE) FROM ECOMMERCE GROUP BY substr(purchase_date,1,4);
CREATE INDEX 
EXPLAIN PLAN FOR   
SELECT substr(purchase_date,1,4),SUM(PRICE) FROM ECOMMERCE GROUP BY substr(purchase_date,1,4);
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());


SELECT substr(purchase_date,6,2),SUM(PRICE) FROM ECOMMERCE  WHERE substr(purchase_date,1,4)=2019
GROUP BY substr(purchase_date,6,2) ORDER BY substr(purchase_date,6,2);
EXPLAIN PLAN FOR SELECT substr(purchase_date,6,2),SUM(PRICE) FROM ECOMMERCE  WHERE substr(purchase_date,1,4)=2019
GROUP BY substr(purchase_date,6,2) ORDER BY substr(purchase_date,6,2);
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());

SELECT COUNTRY,COUNT(*) FROM ECOMMERCE GROUP BY COUNTRY;
EXPLAIN PLAN FOR 
SELECT COUNTRY,COUNT(*) FROM ECOMMERCE GROUP BY COUNTRY;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());

SELECT DISTINCT PRODUCTNAME,substr(purchase_date,1,4) AS YEAR FROM ECOMMERCE 
GROUP BY PRODUCTNAME,substr(purchase_date,1,4) ORDER BY substr(purchase_date,1,4);
CREATE INDEX PRODUCTNAME_PURCHASE_DATE_IDX ON ECOMMERCE(PRODUCTNAME,PURCHASE_DATE);
EXPLAIN PLAN FOR
SELECT DISTINCT PRODUCTNAME,substr(purchase_date,1,4) AS YEAR FROM ECOMMERCE 
GROUP BY PRODUCTNAME,substr(purchase_date,1,4) ORDER BY substr(purchase_date,1,4);
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY()); 